"""Shared typed schemas for document records and labels."""

from __future__ import annotations

from typing import Any, Dict, TypedDict


class RawDocument(TypedDict):
    """Raw document event schema sent to Kafka and stored in HDFS."""

    doc_id: str
    title: str
    content: str
    source: str
    timestamp: str


class LabeledDocument(TypedDict):
    """Auto-labeled document schema generated by Ray + vLLM."""

    doc_id: str
    title: str
    content: str
    source: str
    timestamp: str
    auto_label: str
    confidence: float
    model_name: str
    metadata: Dict[str, Any]
